### ISSUE TITLE
netflix 百度 能看到调用接口但是不显示翻译

### ISSUE THREAD

**Issue by leoleoasd** [ChenYCL/chrome-extension-udemy-translate#1]
![image](https://user-images.githubusercontent.com/37735580/44377343-eabaf600-a52e-11e8-9dd5-adfc95698fbb.png)
但是字幕里并没有显示

**Comment by ChenYCL** [comment]
刚添加完，应该可以了，昨天只做了有道云的配置。@leoleoasd

**Comment by leoleoasd** [comment]
@ChenYCL  现在可以用了  
但是readme里的链接好像也是反着的2333
