### ISSUE TITLE
字幕 沒作用了

### ISSUE THREAD

**Issue by greedtea** [ChenYCL/chrome-extension-udemy-translate#10]
在udemy 按下功能

英文字幕會消失

也沒看到中英對照

**Comment by ChenYCL** [comment]
@greedtea 可以通过这个方式解决下，新版本谷歌需要关闭跨域

Chrome49之后的版本：Windows： 
1.关闭所有的chrome浏览器。
2.新建一个chrome快捷方式，右键“属性”，“快捷方式”选项卡里选择“目标”，添加  --args --disable-web-security --user-data-dir
3.通过快捷方式打开谷歌浏览器

MAC: （mac下暂时没测试，win下ok）
1. 打开终端
2. 输入下面的命令( 需要替换路径中的yourname)

open -n /Applications/Google\ Chrome.app/ --args --disable-web-security  --user-data-dir=/Users/yourname/MyChromeDevUserData/

注意网上有些文章--user-data-dir参数后面没有添加文件夹名，是设置不成功的。
保证该路径/Users/yourname/下存在MyChromeDevUserData文件夹，没有文件夹MyChromeDevUserData，可以自己新建一个

**Comment by greedtea** [comment]
我適用windows 
有加這段 --args --disable-web-security --user-data-dir 
也是不行

 跑去抓舊版 48.0.2564.82 (64-bit)
按了翻譯 沒反應

49是字幕消失

**Comment by ChenYCL** [comment]
具体的点的操作看看这个 https://www.cnblogs.com/huancheng/p/9018162.html
然后谷歌浏览器版本更新下，48是非常古老的版本了，现在多数都是60以上了，同时确保设置的key id有效

**Comment by greedtea** [comment]
我大概知道什麼原因了
三種方式都要使用key id ?
那我用google key id也行嗎?

謝謝

**Comment by ChenYCL** [comment]
谷歌的key id还没做支持。yandex的只要填写key就行了，不用id。百度和有道云需要key id两个填入

**Comment by greedtea** [comment]
google 版本 73.0.3683.103 
我在捷近 後面加 --args --disable-web-security --user-data-dir
沒有跳出警示
key id 我用yandex 跟 百度 

 在 udemy 使用  , 按下翻譯字幕還是消失

**Comment by ChenYCL** [comment]
@greedtea  你有teamview么我远程下，发操作码私邮箱

**Comment by greedtea** [comment]
你的 微信  是多少

要晚上才有空了

ChenYCL <notifications@github.com> 於 2019年4月15日 週一 下午12:04寫道：

**Comment by ChenYCL** [comment]
@greedtea  现在有空没。

**Comment by ChenYCL** [comment]
需要开启跨域已修复

**Comment by st1802002** [comment]
Hi,我也有相同的問題，添加  --args --disable-web-security --user-data-dir
開啟chrome有瀏覽器提示"你在正使用不受支援的命令列標幟: ----disable-web-security。這可能會危及穩定性與安全性"
key id 有測試yandex 跟 百度，百度在統計翻譯的字符數有增加，代表翻譯應該是正常運作
在 udemy 使用 , 按下翻譯字幕一樣會消失
chrome版本 74.0.3729.157 (正式版本) (64 位元)
請問具體的解決方式是什麼?謝謝

**Comment by ChenYCL** [comment]
你重新下载下试试，删除之前的插件先
| |


|
|


|
签名由网易邮箱大师定制


在2019年05月19日 01:35，st1802002<notifications@github.com> 写道：

Hi,我也有相同的問題，添加 --args --disable-web-security --user-data-dir
開啟chrome有瀏覽器提示"你在正使用不受支援的命令列標幟: ----disable-web-security。這可能會危及穩定性與安全性"
key id 有測試yandex 跟 百度，百度在統計翻譯的字符數有增加，代表翻譯應該是正常運作
在 udemy 使用 , 按下翻譯字幕一樣會消失
chrome版本 74.0.3729.157 (正式版本) (64 位元)
請問具體的解決方式是什麼?謝謝

**Comment by st1802002** [comment]
> 你重新下载下试试，删除之前的插件先 在2019年05月19日 01:35，st1802002<notifications@github.com> 写道： Hi,我也有相同的問題，添加 --args --disable-web-security --user-data-dir 開啟chrome有瀏覽器提示"你在正使用不受支援的命令列標幟: ----disable-web-security。這可能會危及穩定性與安全性" key id 有測試yandex 跟 百度，百度在統計翻譯的字符數有增加，代表翻譯應該是正常運作 在 udemy 使用 , 按下翻譯字幕一樣會消失 chrome版本 74.0.3729.157 (正式版本) (64 位元) 請問具體的解決方式是什麼?謝謝 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

移除舊的，重新下載最新版本，可以正常運行了，感謝協助
