### ISSUE TITLE
流媒体串流的时候，翻译的字幕不显示

### ISSUE THREAD

**Issue by ladderhzy** [ChenYCL/chrome-extension-udemy-translate#101]
如题，希望作者加入该功能，以方便串流观看，不胜感激

**Comment by ChenYCL** [comment]
没明白你说的串流是指什么

**Comment by ladderhzy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    串流就是将手机或者电脑上播放的内容通过电视盒子投给电视，没事，我弄懂你的这个插件了，只是叠加了一个文字层，所以你串流的话，它是过不去的，只有视频能过去
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ladderhzy
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年11月14日 ***@***.***> 写道： 




没明白你说的串流是指什么



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
