### ISSUE TITLE
Google翻譯無法呈現

### ISSUE THREAD

**Issue by Kimi191** [ChenYCL/chrome-extension-udemy-translate#116]
版本 v2.1.6 Udemy部分
點開功能後
https://upload.cc/i1/2022/02/11/gJhW7p.png

畫面還是無法翻譯
https://upload.cc/i1/2022/02/11/GBsSaz.png

沒點開功能時
英文字幕是正常的
https://upload.cc/i1/2022/02/11/5XNbfI.png

**Comment by ChenYCL** [comment]
试试api，key相关配置呢，谷歌翻译并不稳定，非第三方服务

**Comment by Kimi191** [comment]
由於我在台灣地區 
很多中國的服務還無法使用~
稍晚會試試Azure Cognitive Services看看

謝謝回應

**Comment by Kimi191** [comment]
妳好

已測試用 Azure 結果仍是相同的
是否還要新增節點的欄位我才能夠使用API呢?

謝謝

![image](https://user-images.githubusercontent.com/98013841/153574519-691c80ed-05d3-4a7c-8be2-3a0ee5649d9c.png)


![image](https://user-images.githubusercontent.com/98013841/153574687-3e840fbc-86bd-49c2-80a7-b820209fe245.png)

**Comment by ChenYCL** [comment]
> 妳好
> 
> 已測試用 Azure 結果仍是相同的 是否還要新增節點的欄位我才能夠使用API呢?
> 
> 謝謝
> 
> ![image](https://user-images.githubusercontent.com/98013841/153574519-691c80ed-05d3-4a7c-8be2-3a0ee5649d9c.png)
> 
> ![image](https://user-images.githubusercontent.com/98013841/153574687-3e840fbc-86bd-49c2-80a7-b820209fe245.png)

当前视频链发下，看看是不是失效了

**Comment by Kimi191** [comment]
> > 妳好
> > 已測試用 Azure 結果仍是相同的 是否還要新增節點的欄位我才能夠使用API呢?
> > 謝謝
> > ![image](https://user-images.githubusercontent.com/98013841/153574519-691c80ed-05d3-4a7c-8be2-3a0ee5649d9c.png)
> > ![image](https://user-images.githubusercontent.com/98013841/153574687-3e840fbc-86bd-49c2-80a7-b820209fe245.png)
> 
> 当前视频链发下，看看是不是失效了

你好 連結如下：

https://www.udemy.com/share/101Wc43@IqhV-PHDrB6r4fwmXjjjCsghp6zR_zFDFKYTpCgpAph2LapkoG5ZunLSY7wrCvyZ/

**Comment by ChenYCL** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/25706676/153718530-df9a08fa-bf95-4718-9fd4-87cb8b15bda7.png">

我这边测试正常
有道云，看看翻译服务对不对，同时刷新下页面

**Comment by Kimi191** [comment]
> <img alt="image" width="765" src="https://user-images.githubusercontent.com/25706676/153718530-df9a08fa-bf95-4718-9fd4-87cb8b15bda7.png">
> 
> 我这边测试正常 有道云，看看翻译服务对不对，同时刷新下页面

了解了
中國的服務目前尚無法申請

感謝
