### ISSUE TITLE
字幕下载功能什么时候能用呢？还有能添加hulu live的翻译功能吗？

### ISSUE THREAD

**Issue by gapeng** [ChenYCL/chrome-extension-udemy-translate#125]
在看hulu live的电视节目直播的时候，发现这个插件的翻译只能翻译那些已经播放结束的节目
直播的时候出现的字幕翻译不了，没有反应，能否解决呢？

很期望字幕下载功能实装！方便第一时间润色烤肉~

真的谢谢大佬了，能做出这么棒的插件来，让我这种对英文半懂不懂的丑八怪能好好啃生肉了。

**Comment by ChenYCL** [comment]
其实之前做好了字幕下载功能，后面感觉涉及到版权问题，关闭了，至于live 有没有账号啥的提供测试，很久没看了；hulu应该是对节点有要求的

**Comment by gapeng** [comment]
> 其实之前做好了字幕下载功能，后面感觉涉及到版权问题，关闭了，至于live 有没有账号啥的提供测试，很久没看了；hulu应该是对节点有要求的

下载字幕的功能有机会通过一些其他渠道打开吗？找不到能下载字幕的软件了已经，谢谢您的工作
我可以给您测试账号，但如何发送呢？
