### ISSUE TITLE
[字幕样式]请问能在字幕样式中加入描边的效果吗？

### ISSUE THREAD

**Issue by gapeng** [ChenYCL/chrome-extension-udemy-translate#127]
现在好像插件里没有为字幕增加描边效果的选项，这导致字幕经常和相同亮度或色彩的视频画面糊到一起
而直接使用那个背景长条又太过于遮挡视频了，
请问能不能增加一个字幕描边的选项呢~谢谢您

**Comment by ChenYCL** [comment]
有背景色透明的选项，之后修改字体颜色
<img width="405" alt="image" src="https://user-images.githubusercontent.com/25706676/167259092-8a700974-f3fc-4775-874a-095460622099.png">

**Comment by gapeng** [comment]
已经尝试过使用透明的背景色了，但太遮挡画面了，另外一个能加字体描边效果的插件还是收费的，所以看看大佬这边能不能更新一个字体描边效果hhhh
