### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by alvinxxxx** [ChenYCL/chrome-extension-udemy-translate#134]
下载后解压，将解压文件导入谷歌浏览器扩展时提示缺少manifest文件，请问是什么原因呢？
<img width="603" alt="image" src="https://user-images.githubusercontent.com/41161802/175087600-3bd46acd-2688-4092-bc39-52ecbbc8fbd2.png">

**Comment by lesenelir** [comment]
要去他的公众号下载，但是没法使用deepl翻译
