### ISSUE TITLE
谷歌插件把你这个插件提示不安全？下架？一直这么提示，要么就自动退出，麻烦查看

### ISSUE THREAD

**Issue by Jinhui1988** [ChenYCL/chrome-extension-udemy-translate#139]
谷歌插件把你这个插件提示不安全？下架？一直这么提示，要么就自动退出，麻烦查看，无论chrome还是edge都是这样

![333](https://user-images.githubusercontent.com/79070282/180143723-c35fecc6-efbc-448d-afc7-2ca14938805c.png)

**Comment by brucezhiyue** [comment]
好久没来，才知道上架了，怎么又下架了？
