### ISSUE TITLE
出现错误，好像是颜色设置不了

### ISSUE THREAD

**Issue by djfly** [ChenYCL/chrome-extension-udemy-translate#15]
The specified value "" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

![QQ图片20190901101621](https://user-images.githubusercontent.com/4409731/64070963-b9c4e380-cca1-11e9-927e-81ff3beec5e8.png)

**Comment by ChenYCL** [comment]
@djfly 请问什么平台下面，翻译的是什么网站，

**Comment by djfly** [comment]
https://www.udemy.com/ 课程
chrome

**Comment by ChenYCL** [comment]
@djfly 我调了下，再试试，初始化的时候之前确实有这问题
