### ISSUE TITLE
udemy translate用户配置有误，或当前接口流量已达上限

### ISSUE THREAD

**Issue by xinchunlai** [ChenYCL/chrome-extension-udemy-translate#16]
这个插件还有用吗？开启中没作用，英文字幕都不显示 ，总是报：用户配置有误，或当前接口流量已达上限

**Comment by ChenYCL** [comment]
@xinchunlai 你好，请问是那个视频站和选择何种api呢？

**Comment by xinchunlai** [comment]
谢谢您的回复，按chrome跨域操作后可以了。

ChenYCL <notifications@github.com> 于2019年10月24日周四 下午1:13写道：
