### ISSUE TITLE
netflix字幕不显示

### ISSUE THREAD

**Issue by littlecutey7** [ChenYCL/chrome-extension-udemy-translate#163]
开启后Netflix字幕不显示，设置填了百度api账号，api也开通了通用文本翻译服务
![image](https://github.com/ChenYCL/chrome-extension-udemy-translate/assets/143382785/6eeff235-c4b1-41f2-a72b-c6ddcee36d78)

**Comment by littlecutey7** [comment]
版本2.1.8

**Comment by lcx189** [comment]
有道云可以
