### ISSUE TITLE
发现有Udemy翻译，很惊喜，却发现用不了。。。

### ISSUE THREAD

**Issue by Zerolucifa0** [ChenYCL/chrome-extension-udemy-translate#17]
先感谢大神开发~
Mac系统。照着说明做了，可以确保ID和Key没有问题（用的Baidu翻译API），但点击翻译就是一点反应也没有
然后发现拓展程序里显示这两个问题

Error handling response: SyntaxError: Unexpected token u in JSON at position 0
options.js:22 (匿名函数)

The specified value "" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
lib/jquery-3.1.1.min.js:4 (匿名函数)

请问下怎么解决？

**Comment by ChenYCL** [comment]
@Zerolucifa0  
1. 需要翻墙
2.百度api测试ok
3.英文字幕cc ，udemy打开英文显示

刚看了下，还可以用，你可以截下图，和课程地址发下先，目前我这边OK

**Comment by Zerolucifa0** [comment]
@ChenYCL 
 
![Xnip2020-01-21_13-45-38](https://user-images.githubusercontent.com/60107460/72810008-b207da80-3c54-11ea-8591-cdfc800a60ca.jpg)
![Xnip2020-01-21_13-46-10](https://user-images.githubusercontent.com/60107460/72810016-b502cb00-3c54-11ea-9f86-ac5e4850903f.jpg)
![Xnip2020-01-21_13-41-57](https://user-images.githubusercontent.com/60107460/72810023-b7652500-3c54-11ea-8f0f-ff381e427b29.jpg)

百度翻译API测试？我去学一下。。。我电脑小白
课程是Udemy的Vector Calculus (Div Grad Curl)

**Comment by ChenYCL** [comment]
@Zerolucifa0 
![image](https://user-images.githubusercontent.com/25706676/72810727-1e0c3200-3c99-11ea-98b8-24ff5589d4a5.png)
我这边OK ，不过用的是有道云的，你id key重填写下，设置里面点击应用，刷新下看看
aa34913@gmail.com  联系吧

**Comment by Zerolucifa0** [comment]
我知道原因了
字幕设置里，取消字幕显示在视频最下方，翻译就出来了
谢谢大神~ @ChenYCL
