### ISSUE TITLE
能否添加对Disneyplus的支持

### ISSUE THREAD

**Issue by skinnydruid** [ChenYCL/chrome-extension-udemy-translate#18]
Disneyplus已经上线一段时间，没有中文字幕，能否添加对Disneyplus支持

**Comment by ChenYCL** [comment]
@skinnydruid 需要账号，可以的话发我邮箱，试试

**Comment by skinnydruid** [comment]
> @skinnydruid 需要账号，可以的话发我邮箱，试试



> @skinnydruid 需要账号，可以的话发我邮箱，试试

账号已经发你邮箱，本人自用的

**Comment by 666keke** [comment]
请问适配工作完成了吗）

**Comment by Kuroneko209** [comment]
同问，disneyplus可以添加支持吗？

**Comment by Weber0824** [comment]
同问

**Comment by ChenYCL** [comment]
#22 已完成

**Comment by ChenYCL** [comment]
disney plus 不用打开字幕cc
