### ISSUE TITLE
[建议]能否做成油猴子脚本？

### ISSUE THREAD

**Issue by Randomseed233** [ChenYCL/chrome-extension-udemy-translate#19]
greasyfork.org上有人给Lynda视频网做了油猴子脚本，添加中文字幕，功能与这个类似；
不知道是否可以把这个插件做成油猴子脚本？

**Comment by ChenYCL** [comment]
开了一个头，现在这段时间应该不会有时间重构了

**Comment by zwxharry2018** [comment]
> 开了一个头，现在这段时间应该不会有时间重构了

期待
