### ISSUE TITLE
在hulu使用时会发生漏词、跳句

### ISSUE THREAD

**Issue by 666keke** [ChenYCL/chrome-extension-udemy-translate#21]
尝试了百度和Yandex的API，都有这个问题

**Comment by 666keke** [comment]
能否直接提取视频中的vtt字幕文件，整个文档翻译后替用，应该可以预防这类事件

**Comment by ChenYCL** [comment]
@666keke 重构版本，帮忙测试下，目前没有账号
https://github.com/ChenYCL/chrome-extension-udemy-translate/releases/tag/v2.0.1
