### ISSUE TITLE
在netflix无法支持日语和韩语，请支持

### ISSUE THREAD

**Issue by ybnedsi** [ChenYCL/chrome-extension-udemy-translate#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChenYCL** [comment]
https://github.com/ChenYCL/chrome-extension-udemy-translate/releases/tag/v2.0.1
这个版本可选择日语或者韩语，已做日语测试，可以测试下，如有问题可反馈 
提供的样式为 原字幕+译文,译文支持多语言

**Comment by ybnedsi** [comment]
> https://github.com/ChenYCL/chrome-extension-udemy-translate/releases/tag/v2.0.1
> 这个版本可选择日语或者韩语，已做日语测试，可以测试下，如有问题可反馈
> 提供的样式为 原字幕+译文,译文支持多语言

英语、葡萄牙语都是正常的，但是切换到日韩就不行了，会卡在先前英语界面，无翻译
<img width="637" alt="1" src="https://user-images.githubusercontent.com/58318061/78632909-cf9f2480-78d2-11ea-9174-ceead3804327.png">
<img width="633" alt="2" src="https://user-images.githubusercontent.com/58318061/78632910-d168e800-78d2-11ea-85cc-76fa1535bdeb.png">

**Comment by ChenYCL** [comment]
配置生效后，刷新一次页面再看看

**Comment by ChenYCL** [comment]
![image](https://user-images.githubusercontent.com/25706676/78640816-9074d180-78da-11ea-8660-41d0df6c9871.png)
英文->韩 显示正常

**Comment by ChenYCL** [comment]
![image](https://user-images.githubusercontent.com/25706676/78641115-e9dd0080-78da-11ea-9ac1-47908c1aabd1.png)
英文->日 ok  配置语言切换后，需要等1-2s ，没有刷新页面我这边，而且有几率失效，目前

**Comment by ybnedsi** [comment]
> ![image](https://user-images.githubusercontent.com/25706676/78641115-e9dd0080-78da-11ea-9ac1-47908c1aabd1.png)
> 英文->日 ok 配置语言切换后，需要等1-2s ，没有刷新页面我这边，而且有几率失效，目前

谢谢大佬，其它语言转日韩文没有问题，就是日韩文转其它语言有问题。

 

> 当前视频页面类型: netflix
> contentScript.bundle.js:1 Content script works!
> contentScript.bundle.js:1 Must reload extension for modifications to take effect.
> contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using a function from the Print Module
> cast_sender.js:2 GET chrome-extension://invalid/ net::ERR_FAILED
> cast_sender.js:2 GET chrome-extension://invalid/ net::ERR_FAILED
> none:6 No cast extension found
> ﻿

​

**Comment by ChenYCL** [comment]
这个后面应该能解决掉，目前猜测，无法识别源语言，加个当前源语言选项就行了

**Comment by ybnedsi** [comment]
> 个当前源语言选项就行

辛苦了，谢谢。
下面是chrome 的调试记录
DevTools failed to parse SourceMap: chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map
8
[Violation] 'setTimeout' handler took <N>ms
[Violation] 'setTimeout' handler took 90ms
[Violation] 'setTimeout' handler took 109ms
none:7 [Violation] 'setTimeout' handler took 56ms
[Violation] 'setTimeout' handler took 154ms
cadmium-playercore-6.0022.420.011.js:1 [Violation] 'setTimeout' handler took 54ms
[Violation] 'setTimeout' handler took 115ms
cadmium-playercore-6.0022.420.011.js:1 [Violation] 'setTimeout' handler took 54ms
[Violation] 'setTimeout' handler took 125ms
10
[Violation] Forced reflow while executing JavaScript took <N>ms
[Violation] Forced reflow while executing JavaScript took 81ms
[Violation] Forced reflow while executing JavaScript took 98ms
[Violation] Forced reflow while executing JavaScript took 483ms
[Violation] Forced reflow while executing JavaScript took 43ms
[Violation] Forced reflow while executing JavaScript took 129ms
[Violation] Forced reflow while executing JavaScript took 211ms
[Violation] Forced reflow while executing JavaScript took 31ms
[Violation] Forced reflow while executing JavaScript took 107ms
[Violation] Forced reflow while executing JavaScript took 304ms
[Violation] Forced reflow while executing JavaScript took 117ms

**Comment by denyot** [comment]
我这用的2.1版本，从日语到中文简字也不行。  英语到中文正常

**Comment by nancheung97** [comment]
日韩翻译到中字确实不行，试了好几个版本
