### ISSUE TITLE
重构新版帮忙测试下

### ISSUE THREAD

**Issue by ChenYCL** [ChenYCL/chrome-extension-udemy-translate#24]
因为amazon，hbo now ，primevideo，hulu 目前没有账号，请有账号的朋友自行测试，重构版本，未作测试，如果可以，可在下方留言，谢谢

[分支](https://github.com/ChenYCL/chrome-extension-udemy-translate/tree/v2.0.0)
[下载](https://github.com/ChenYCL/chrome-extension-udemy-translate/releases)

**Comment by 666keke** [comment]
重构版本hulu无法翻译

**Comment by 666keke** [comment]
重构版本primevideo无法翻译

**Comment by 666keke** [comment]
重构版本Netflix翻译正常

**Comment by ChenYCL** [comment]
@666keke 可以支援下账号测试么，没通的

**Comment by 666keke** [comment]
> @666keke 可以支援下账号测试么，没通的

已经通过邮件发送了

**Comment by LM-Firefly** [comment]
设置不能够保存 关掉Netflix窗口再进去 设置就重置了

**Comment by ChenYCL** [comment]
配置id吧 粘贴了之后 空格一下再删除，直接粘贴没做记录，手动输入模拟

**Comment by LM-Firefly** [comment]
> 配置id吧 粘贴了之后 空格一下再删除，直接粘贴没做记录，手动输入模拟

不能记住字体大小、字幕背景的设置，而且我的接口选的是Google 每次都会重置到 空白的有道云api

**Comment by ChenYCL** [comment]
谷歌接口ip限次，目前 200次/ 1h 内，基本没啥作用，字体大小，字幕保存无问题，最新版本试试
primevideo，hulu 已修复

**Comment by ChenYCL** [comment]
重构版本结束
