### ISSUE TITLE
拉进扩展程序显示错误

### ISSUE THREAD

**Issue by Kuroneko209** [ChenYCL/chrome-extension-udemy-translate#29]
未能成功加载扩展程序
文件
~/下载/chrome-extension-udemy-translate-master
错误
清单文件缺失或不可读取
无法加载清单。

**Comment by shifeid** [comment]
一样，如何解决了

**Comment by lafayatte** [comment]
选择在里面那个文件.\udemy-translate\**udemy-translate** 这个文件
