### ISSUE TITLE
请教Hbo Now 翻译显示的问题

### ISSUE THREAD

**Issue by gykai** [ChenYCL/chrome-extension-udemy-translate#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
您好，非常感谢您开发了这么优秀的程序。
有个问题想请教一下，目前测试Netflix和hulu正常，但是不知道为什么hbo now有问题，只能翻译出第一句话，后续的就不再显示了，而且第一句翻译出来的内容会一直显示在屏幕上，后面的原文字幕会继续显示，但不再翻译了。系统是win10 64位企业版，翻译的程序选过谷歌和百度，但都不能正常使用。再次感谢！

**Comment by ChenYCL** [comment]
嗯 重构没注意，这个是有问题的，等解决

**Comment by ChenYCL** [comment]
@gykai hbo修复
