### ISSUE TITLE
請問如何安裝？

### ISSUE THREAD

**Issue by MiloCT** [ChenYCL/chrome-extension-udemy-translate#32]
我按照了你的說明圖片到擴充功能開啟開發者模式，然後不知道要怎麼把下載的檔案做進一步的使用？因為圖片完全沒有說明，而我是第一次使用，可以麻煩告知嗎？ 謝謝

**Comment by ChenYCL** [comment]
当解压完成后，选择加载解压的程序
![image](https://user-images.githubusercontent.com/25706676/79181848-92d5af00-7e37-11ea-87f6-eedad7c38f60.png)

2.之后右上角插件栏能看到相应的配置选项

**Comment by MiloCT** [comment]
<img width="522" alt="截圖 2020-04-14 下午7 47 40" src="https://user-images.githubusercontent.com/32704466/79212893-a3b01000-7e8b-11ea-9fc5-1cea71ace19f.png">
<img width="518" alt="截圖 2020-04-14 下午7 48 01" src="https://user-images.githubusercontent.com/32704466/79212898-a6ab0080-7e8b-11ea-9015-f8afc60a5d2a.png">

您好我嘗試您教的操作了，但出現這個錯誤不知道有何解？謝謝

**Comment by ChenYCL** [comment]
你好请重新下载下吧， 我这边测试ok 事mac上面吧看这个

**Comment by ChenYCL** [comment]
https://github.com/ChenYCL/chrome-extension-udemy-translate/blob/master/README_zh.md <https://github.com/ChenYCL/chrome-extension-udemy-translate/blob/master/README_zh.md>

**Comment by MiloCT** [comment]
是在這裡
https://github.com/ChenYCL/chrome-extension-udemy-translate/releases/tag/v2.0.2
下載
udemy-translate.zip
對嗎？
謝謝

**Comment by ChenYCL** [comment]
对的 直接下那个。zip的解压到文件夹，导入

**Comment by MiloCT** [comment]
重新下載一次可以了，不過我實際用了您的這個工具

字幕翻譯還是會先看到英文字在閃成中文字，跟原本沒有用的情況是一樣的

不知道您這個工具實際提供了什麼功能？

PS.現在Udemy的字幕似乎一定要把字幕設為影片下顯示 否則不會正常翻譯 

我有把我的問題錄製成一個短片您應該會比較好理解
https://www.youtube.com/watch?v=KuofsMRRNjo&feature=youtu.be
1-20主要是在呈現當開啟您的工具之後，字幕會消失
20秒之後再呈現必須把字幕設為影片下顯示才會翻譯字幕
而使用您的工具跟沒有用在翻譯上一樣都會有延遲看到原始英文字

再麻煩您查看 謝謝

**Comment by ChenYCL** [comment]
是需要设置在影片下才行，中文问题 应该是同时开了谷歌翻译的缘故，可以打开开关后再刷新一次 
    	
    	

    	获取 Outlook for iOS
    
  




On Wed, Apr 15, 2020 at 2:40 PM +0800, "MiloCT" <notifications@github.com> wrote:















重新下載一次可以了，不過我實際用了您的這個工具


字幕翻譯還是會先看到英文字在閃成中文字，跟原本沒有用的情況是一樣的


不知道您這個工具實際提供了什麼功能？


PS.現在Udemy的字幕似乎一定要把字幕設為影片下顯示 否則不會正常翻譯


我有把我的問題錄製成一個短片您應該會比較好理解

https://www.youtube.com/watch?v=KuofsMRRNjo&feature=youtu.be

1-20主要是在呈現當開啟您的工具之後，字幕會消失

20秒之後再呈現必須把字幕設為影片下顯示才會翻譯字幕

而使用您的工具跟沒有用在翻譯上一樣都會有延遲看到原始英文字


再麻煩您查看 謝謝

**Comment by MiloCT** [comment]
抱歉，請容我先釐清一下，您這個程式我記得我看到的功能是：
在用Google翻譯Udemy的時候 總是會先顯示原文在呈現中文，而您的程式則是可以讓原文的部份不呈現僅呈現中文的部份？ 不知道這點我有沒有理解錯誤？

因為我如果只開您的程式，那僅會顯示原文（英文） 就沒辦法進行同步中文翻譯了

**Comment by ChenYCL** [comment]
是双字幕的，英文在上，中文在下。  英文字幕 udemy自带有，这个只是原字幕+英文字幕一起显示。

**Comment by MiloCT** [comment]
了解，所以Udemy本身影片如果沒有中文字幕的話 就沒辦法用這個了 我誤會了QQ 難怪沒效果
