### ISSUE TITLE
win7 64sp1 chrome 版本 81.0.4044.113(64位)上老是没法保存api没有保存按钮

### ISSUE THREAD

**Issue by wxdjs** [ChenYCL/chrome-extension-udemy-translate#36]
**Describe the bug**
当hulu.com没有浏览时，此时点击插件显示开启状态，
当浏览hulu时，插件默认又关闭了，打开后点击右上角设置，里面api值已经清空
还有字幕位置没有调整的地方
**Desktop (please complete the following information):**
 - OS: [win7 64 sp1]
 - Browser [Chrome]
 - Version [81.0.4044.113(64位)]

**Comment by ChenYCL** [comment]
丢失配置已尝试修复，最新版本替换试试。

**Comment by fsjinyu** [comment]
版本2.02 win10更新到最新 chrome更新到最新 同样遇到一样的问题 插件自己关闭，api已经清空。有时看着切换一下chrome的sheet再回来又关闭了

**Comment by ChenYCL** [comment]
@fsjinyu 试试最新的 看看
