### ISSUE TITLE
谢谢！hbo看双字幕非常好用，作者能放到Chrome 网上应用店吗？

### ISSUE THREAD

**Issue by brucezhiyue** [ChenYCL/chrome-extension-udemy-translate#37]
如题，谢谢！非常好用，hbo看双字幕非常好用，作者能放到Chrome 网上应用店吗？是不能通过审核吗？

选择透明背景时，有时会有小方块出现在字幕背景上，不影响使用。

谢谢，插件非常好！

**Comment by ChenYCL** [comment]
是要钱..应该还有一些资料吧

**Comment by Shuyakano** [comment]
能否做个插件设置动态背景页开关、每次打开插件设置页面、CPU 占用暴增、页面滚动也会卡顿！感谢~

**Comment by brucezhiyue** [comment]
> 是要钱..应该还有一些资料吧
建议可以的话上市场，大家可以给你捐点，你自己垫点，等市场上的下载量起来以后可以考虑平价付费或者平价订阅模式，支持你，希望这个插件越来越好。👍

**Comment by ChenYCL** [comment]
@Shuyakano 恩 可以，动态用的threejs 是吃打资源，有点花销

**Comment by ChenYCL** [comment]
@brucezhiyue 恩 谢谢建议

**Comment by brucezhiyue** [comment]
> @brucezhiyue 恩 谢谢建议

谢谢！

**Comment by ChenYCL** [comment]
加了
