### ISSUE TITLE
cpu 占用率高 BUG

### ISSUE THREAD

**Issue by xingyunauthor** [ChenYCL/chrome-extension-udemy-translate#39]
我有台2015款的 macbook pro 13，在使用这个插件观看Netflix视频的时候，cpu占用率达到了50%，而且页面也出现了卡顿的情况，我的建议如下图
![image](https://user-images.githubusercontent.com/25634235/80169133-3fbde200-8617-11ea-9f38-fc3265478799.png)

这样修改后，cpu 的占用率明显下去了

**Comment by ChenYCL** [comment]
在Netflix下已使用这种方式，不过在Primevideo测试过程中，发现一个问题，当字幕切换过快，会出现漏句的情况，先尝试在netlfix下使用这种监听dom的方式试试，其它的目前保持不变。
