### ISSUE TITLE
字幕样式建议（sub style suggestion）

### ISSUE THREAD

**Issue by ChenYCL** [ChenYCL/chrome-extension-udemy-translate#4]
字幕样式有什么好的建议欢迎讨论，目前考虑到视频白色区域有点，还是加了黑色的底色。

**Comment by zhouyongtao** [comment]
希望底色可以选择，有的时候透明比较好一些。

**Comment by Liqianyu** [comment]
底色和字幕透明度可以分开调整比较好。字幕颜色和画面背景颜色重叠时不利于观看。如果可以实现字幕描边等效果是最佳解决方案。

**Comment by ChenYCL** [comment]
@Liqianyu 好的，后面加上描边
