### ISSUE TITLE
“请检查配置，或者账号欠费到期等”

### ISSUE THREAD

**Issue by tokentaker** [ChenYCL/chrome-extension-udemy-translate#43]
为什么hulu在没有对白的时候会出现“请检查配置，或者账号欠费到期等”字幕？用的百度api高级版。

**Comment by ChenYCL** [comment]
可以截图看看，一般情况是网络问题，出现这个的时候，英文字幕有没有

**Comment by tokentaker** [comment]
![hulu](https://user-images.githubusercontent.com/62585812/80296796-74b16c80-87b0-11ea-9857-e7f03a45d5af.png)
对白正常翻译，就是在对白间歇会出现这个提示。检查网络没什么问题。

**Comment by ChenYCL** [comment]
那可能是 空白无法翻译，我去看看

**Comment by tokentaker** [comment]
感谢，有强迫症，哈哈，搞好给您发红包。

**Comment by tokentaker** [comment]
刚又测试了hulu的一些片源，都没有问题。貌似就 The Strain 这个剧会出现这个提示，真是奇怪。

**Comment by ChenYCL** [comment]
看看有没有上面奇怪的字幕格式没 这个

**Comment by tokentaker** [comment]
![hulu](https://user-images.githubusercontent.com/62585812/80299176-e5628400-87c4-11ea-9d10-b30c0fc18d0e.png)
发现了个问题，对白间隙字幕依然会有个无字框，这个框会翻译成“请检查配置，或者账号欠费到期等”，我看了别的片源都没有这个框。

**Comment by ChenYCL** [comment]
可以审查下元素 检查元素，看看是什么字符 （ ？ 这种么
 ，直接做个判断，我后面好加个 直接去掉

**Comment by tokentaker** [comment]
我找不到这个字符，我把hulu的账号发你Gmail了，麻烦帮忙看下，片源在MY STUFF里有保存，The Strain。

**Comment by ChenYCL** [comment]
嗯 晚点看看

**Comment by ChenYCL** [comment]
试试现在还有这个问题没

**Comment by tokentaker** [comment]
没问题了，发了个小红包感谢！希望以后能增加翻译hulu live tv电视台的字幕。
