### ISSUE TITLE
无法成功添加插件

### ISSUE THREAD

**Issue by tangguo-guo** [ChenYCL/chrome-extension-udemy-translate#44]
清单文件缺失或不可读取
无法加载清单。

**Comment by tangguo-guo** [comment]
请问是怎么回事呢

**Comment by ChenYCL** [comment]
https://github.com/ChenYCL/chrome-extension-udemy-translate/releases 这里下udemy-translate.zip 解压添加文件夹，谷歌或者EDGE新版浏览器。

**Comment by tangguo-guo** [comment]
![image](https://user-images.githubusercontent.com/64531774/80684502-5a50f900-8af8-11ea-8299-2ca2222f586e.png)
请问怎么字幕占这么宽的位置啊，可以修改设置吗

**Comment by tangguo-guo** [comment]
您好，问题已解决。把背景设为透明了就好了，谢谢开发这么好程序
![image](https://user-images.githubusercontent.com/64531774/80686119-d3515000-8afa-11ea-9d1b-737eb14fad25.png)
