### ISSUE TITLE
美区amazon video无法翻译

### ISSUE THREAD

**Issue by tokentaker** [ChenYCL/chrome-extension-udemy-translate#45]
美区的amazon video需要从www.amazon.com网页进入prime video进行观看，但是用插件不能翻译。插件只能翻译www.primevideo.com上的资源，但是通过这个网站访问需是美区以外的地区。麻烦帮忙看下能否解决美区的翻译？感谢！

**Comment by ChenYCL** [comment]
@tokentaker 有账号提供下么，还有美区的amazon.com 视频地址来一个，主要是美区网址有改变没，同primevideo的区别

**Comment by tokentaker** [comment]
> @tokentaker 有账号提供下么，还有美区的amazon.com 视频地址来一个，主要是美区网址有改变没，同primevideo的区别

入口有区别，美区的入口是https://www.amazon.com/gp/video/storefront/ref=sv_atv_logo?node=2858778011，账号我邮件发你。

**Comment by tokentaker** [comment]
大佬能帮忙看看吗？美区无法翻译。

**Comment by ChenYCL** [comment]
已添加
