### ISSUE TITLE
翻译的时候总是显示：请检查配置，或者账号欠费到期等！

### ISSUE THREAD

**Issue by yanga9** [ChenYCL/chrome-extension-udemy-translate#46]
在字幕空闲时，总是显示“请检查配置，或者账号欠费到期等”，chrome-extension-udemy-translate-1.13以前版本没有显示

**Comment by ChenYCL** [comment]
这个要分情况了 用什么翻译方式，什么网站，一般是翻译失败才会导致这个问题，先更新下试试 最新的

**Comment by yanga9** [comment]
用的是百度云API，它只在没有字幕的时候显示，有字幕翻译的时候不会出来，不影响正常字幕翻译，但总是看到显示“请检查配置，或者账号欠费到期等”眼睛很累，重构版本后，从2.0开始的所有版本我都试了，看netflix都是显示的。1.13以前版本的都没有这个问题，但那个双字幕占地方多，看着也累。

**Comment by ChenYCL** [comment]
什么视频站，可以解决下
是字幕为空的时候么？这个我记得之前修复了 你下的最新的版本么

**Comment by yanga9** [comment]
是最新版本，看netflix，只要用2.0以后版本的插件翻译都有这个问题，只在字幕为空的时候显示。

**Comment by ChenYCL** [comment]
你测试下 有道云和yandex看看

**Comment by yanga9** [comment]
好的，我先注册个有道云试下先

**Comment by ChenYCL** [comment]
可以关注我公众号 看教程 推广下 😄 回复 翻译工具

**Comment by yanga9** [comment]
我刚刚注册了有道云试了，没有显示“请检查配置，或者账号欠费到期等”

**Comment by yanga9** [comment]
你的公众号是什么？我加下

**Comment by ChenYCL** [comment]
**影音下午茶**    等下修复版本准备放公众号了  尝试做一个资源整合 ，也算是努力下吧，程序员的生涯终归还是太乏力了点

**Comment by yanga9** [comment]
好的，兄弟这个插件其实用户群挺大的，其实可以在插件上添加个公众号，引流下

**Comment by ChenYCL** [comment]
搞定了 你试试 公众号回复 工具下载  获取百度盘链接
这周有时候 加上一个人工智能api 看看， 拟人化翻译

**Comment by tokentaker** [comment]
2.0.6翻译奈飞没遇到这个问题，倒是遇到一段对话说完最后一句字幕还挂着不消失直到下一段话开始，大佬能帮忙看看怎么回事吗？

**Comment by ChenYCL** [comment]
@tokentaker #40  参照这个，后期看情况考虑，一些笔记本会发热发烫 相对来说
