### ISSUE TITLE
朋友们，可以的话帮忙关注下公众号，生活不易，谢谢

### ISSUE THREAD

**Issue by ChenYCL** [ChenYCL/chrome-extension-udemy-translate#47]
### 定期分享一些视频影音和有用的资源资讯

公众号里有比较详细的教程 关于有道的，相对有道翻译比较好用点，个人觉得，但是流程相对复杂

![image](https://user-images.githubusercontent.com/25706676/82330710-c5199400-9a15-11ea-9c8a-85ce4e846a55.png)

**Comment by yolo0716** [comment]
工具下载
