### ISSUE TITLE
不支持最新的HBO MAX

### ISSUE THREAD

**Issue by dancwj** [ChenYCL/chrome-extension-udemy-translate#48]
HBO MAX今天刚刚推出来，看了一下，不支持翻译。

**Comment by ChenYCL** [comment]
和hbo now是同一账号么，可提供账号看看能不能做支持

**Comment by dancwj** [comment]
> 和hbo now是同一账号么，可提供账号看看能不能做支持

hbo now自动升级为max，所以用hbo now账户就可以登陆hbo max，www.hbomax.com

**Comment by shwsh** [comment]
是的，很奇怪，我用了相同的电影进行测试，hbo now可以正常使用翻译，但是hbo max却不行

**Comment by ChenYCL** [comment]
需要一个测试账号，来看看

**Comment by Liketaya** [comment]
apple tv+里面提供7天试用,可以试试

**Comment by Liketaya** [comment]
> 需要一个测试账号，来看看

apple tv+里面提供7天试用,可以试试

**Comment by ChenYCL** [comment]
添加支持了
