### ISSUE TITLE
亚马逊视频不支持翻译

### ISSUE THREAD

**Issue by ShadowsSide** [ChenYCL/chrome-extension-udemy-translate#49]
试过netflix翻译没问题，我是印度区的亚马孙视频。
![亚马逊](https://user-images.githubusercontent.com/61958350/83267092-4fbc7900-a1f6-11ea-91bf-63c26c30eae9.png)

**Comment by ShadowsSide** [comment]
使用的是百度api。

**Comment by ChenYCL** [comment]
印度区 网址是多少

**Comment by ShadowsSide** [comment]
我登录显示的是这个https://www.primevideo.com/region/eu

ChenYCL <notifications@github.com>于2020年5月29日 周五下午10:33写道：

**Comment by ChenYCL** [comment]
下载新版试试

**Comment by ShadowsSide** [comment]
好的。谢谢作者！

**Comment by ShadowsSide** [comment]
翻译成功了！谢谢

犬来八荒 <a84552179@gmail.com>于2020年5月31日 周日下午1:35写道：
