### ISSUE TITLE
chrome解压文件失败

### ISSUE THREAD

**Issue by shengwuli** [ChenYCL/chrome-extension-udemy-translate#51]
下载文件后，开启chrom开发者模式后失败

**Comment by ChenYCL** [comment]
当前版本 https://github.com/ChenYCL/chrome-extension-udemy-translate/releases/tag/v2.0.6 可以。2.0.6后版本不行

**Comment by shengwuli** [comment]
谢谢了

ChenYCL <notifications@github.com> 于 2020年6月11日周四 11:09写道：
