### ISSUE TITLE
无法翻译

### ISSUE THREAD

**Issue by ichliebecmr** [ChenYCL/chrome-extension-udemy-translate#57]
如题，按照教程一一填写了百度、有道云账号密码，但是每次打开插件还是无法翻译视频中的英文对话内容，Netflix、Prime Video都试过了，没有反应。更有趣的是每次打开翻译插件之后，视频中的原生英文字幕都莫名消失；关掉插件，原生英文字幕才会蹦出来了。
所以，就我一个人遇到这种问题了？？？。。。

**Comment by ChenYCL** [comment]
你好测试了下netflix，无问题。建议查看账号是否正确，开启后刷新一下网页
![image](https://user-images.githubusercontent.com/25706676/91802324-41e71b80-ec5d-11ea-814d-f801357e5c17.png)

**Comment by BeBubbled** [comment]
在注册完百度翻译api后, 完成认证, 还需要向百度申请开通api服务,
<img width="1019" alt="Screen Shot 2021-03-06 at 4 06 55 PM" src="https://user-images.githubusercontent.com/57272656/110220828-47385380-7e96-11eb-984b-cc55ba541d9d.png">, 你需要看到至少一项翻译服务正在启用, 例如我启用了"通用翻译API", 否则的服务费启用, api返回无效值, 你的字幕会消失
