### ISSUE TITLE
hulu字幕翻译一闪而过

### ISSUE THREAD

**Issue by Itsianwong** [ChenYCL/chrome-extension-udemy-translate#58]
打开Udemy翻译后看hulu字幕都是一闪而过，已尝试更换翻译源、文字大小及背景均无法解决。

**Comment by ChenYCL** [comment]
其它片源有这种问题么

**Comment by Liketaya** [comment]
一样的问题,其他的如HBO的没有这种问题

**Comment by ieloug1** [comment]
出现了同样的问题，可帮忙测试。

**Comment by ChenYCL** [comment]
@ieloug1 有账号提供测试下么 hulu的

**Comment by ieloug1** [comment]
> @ieloug1 有账号提供测试下么 hulu的 ，同时有问题的片源，不过前提条件是需要当前视频有cc字幕

可以提供账号。目前测试了“the sopranos”和“euphoria”（首页有播放记录），均可以开启英文cc字幕。

**Comment by ChenYCL** [comment]
> > @ieloug1 有账号提供测试下么 hulu的 ，同时有问题的片源，不过前提条件是需要当前视频有cc字幕
> 
> 可以提供账号。目前测试了“the sopranos”和“euphoria”（首页有播放记录），均可以开启英文cc字幕。

嗯嗯，私发下邮箱就好了

**Comment by ieloug1** [comment]
> > > @ieloug1 有账号提供测试下么 hulu的 ，同时有问题的片源，不过前提条件是需要当前视频有cc字幕
> > 
> > 
> > 可以提供账号。目前测试了“the sopranos”和“euphoria”（首页有播放记录），均可以开启英文cc字幕。
> 
> 嗯嗯，私发下邮箱就好了

已发

**Comment by ChenYCL** [comment]
修复了 更新新版看看

**Comment by ieloug1** [comment]
> 修复了 更新新版看看

您公众号好像还没更新下载链接

**Comment by ChenYCL** [comment]
> > 修复了 更新新版看看
> 
> 您公众号好像还没更新下载链接

源文件替换了

**Comment by ieloug1** [comment]
> > > 修复了 更新新版看看
> > 
> > 
> > 您公众号好像还没更新下载链接
> 
> 源文件替换了

之前的链接显示分享文件被取消了

**Comment by ChenYCL** [comment]
已经更新了 1.0版本
