### ISSUE TITLE
edge浏览器播放disney+时，插件显示的字幕有一个大大的黑底

### ISSUE THREAD

**Issue by xiaoaozhangfu** [ChenYCL/chrome-extension-udemy-translate#62]
edge浏览器播放disney+时，插件显示的字幕有一个大大的黑底
如图所示：
[https://i.loli.net/2020/11/19/GpeE7LKV69Qobkg.png](url)

我希望作者能改进的是：
1，消除这个黑底，我尝试调节透明度，无效
2，如何设置显示1字幕或者2字幕？图中实际上有三个字幕了（插件显示两个字幕，还有一个disney自带的英文字幕给黑底挡住了）

环境：
win7
edge浏览器86.0.622.69
插件是最新的2.10

**Comment by ChenYCL** [comment]
黑底可以设置背景色为透明的,第一个为透明,目前只提供双字幕同时显示.其中原字幕被插件字幕接管,至于原字幕,正常情况应该不会显示的

**Comment by xiaoaozhangfu** [comment]
谢谢回复，确实，我现在按你法子设置为透明底可以解决问题，并且我关闭了Disney的字幕显示，就变成中英双字幕了，目前还不错，希望未来能像Netflix，apple tv+那样，有透明底效果
