### ISSUE TITLE
Not working on Hulu

### ISSUE THREAD

**Issue by Liqianyu** [ChenYCL/chrome-extension-udemy-translate#63]
**Describe the bug**
Subtitles were not translated and nothing happened.

**To Reproduce**
1. Go to 'https://www.hulu.com/'
2. Click on 'Arbitrary Video'
3. Open Plugin

**Expected behavior**
The original English subtitles are shown against the machine-translated Chinese subtitles.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome canary]
 - Version [89]

**Additional context**
Disney+ streaming works fine.

**Comment by ChenYCL** [comment]
嗯,私发邮箱吧

**Comment by xiaoaozhangfu** [comment]
我也发现了，hulu看不了中文字幕，浏览器是edge，win7系统。同等环境下，Disney+ ok。

**Comment by ChenYCL** [comment]
#68 macos 下chrome正常,edge理论上内核相同

**Comment by ChenYCL** [comment]
#68 same issue
