### ISSUE TITLE
字幕的透明度无论调解成多少，都是100%，会‘遮挡到画面，不知道能不能解决一下，谢谢！有图

### ISSUE THREAD

**Issue by zydchina818** [ChenYCL/chrome-extension-udemy-translate#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/28103084/101976171-9c8d0c00-3c7d-11eb-9043-b8798aecf4e6.png)

**Comment by zydchina818** [comment]
[
![屏幕截图 2020-12-12 132340](https://user-images.githubusercontent.com/28103084/101976187-bdedf800-3c7d-11eb-81e0-a50af3ae3920.png)
](url)

**Comment by ChenYCL** [comment]
#62 目测是这个问题,参照下试试

**Comment by ChenYCL** [comment]
暂时先关了,如果未解决再reopen

**Comment by ChenYCL** [comment]
![image](https://user-images.githubusercontent.com/25706676/103365842-f9047e00-4afb-11eb-9816-4df0ecb78336.png)
简单的演示关闭效果
#68
