### ISSUE TITLE
希望能够支持日语,韩语翻译.

### ISSUE THREAD

**Issue by qq1840083132** [ChenYCL/chrome-extension-udemy-translate#69]
现在日区Netflix几乎都是日语,没有日语翻译真的很不方便,希望能够添加这个功能,十分感谢!

**Comment by ChenYCL** [comment]
之前试过,日语字幕是图片来的,ocr翻译效果识别度不高,而且需要开额外服务去做.再看看吧,基本上插件层次比较难搞,一直在空着

**Comment by hyunsuk7866** [comment]
用他这个 插件 好像 可以获取 日语字幕。。不知道是什么方式 
https://chrome.google.com/webstore/detail/language-learning-with-ne/hoombieeljmmljlkjmnheibnpciblicm
