### ISSUE TITLE
你好！能否让它支持hbo now 和hulu  prime video等 

### ISSUE THREAD

**Issue by brokenman1** [ChenYCL/chrome-extension-udemy-translate#7]
非常感谢您开发出这样好的插件，能否让它支持hbo now 和hulu  prime video等  特别需要它

**Comment by ChenYCL** [comment]
@brokenman1 有测试账号给我试试么，发我邮箱吧

**Comment by brokenman1** [comment]
https://www.hulu.com <https://www.hulu.com/>

dingqing6052732@163.com
gG123666

Amazon video

账号密码：dangua818@163.com----f78783368

HBO now:
账号 Buy1HBONOW@TBSS.CHWYYSJ <mailto:Buy1HBONOW@TBSS.CHWYYSJ> 密码chwyysj12

**Comment by ChenYCL** [comment]
这个私发就好了，明天看看

**Comment by brokenman1** [comment]
好的 非常感谢 亲 你wx多少

**Comment by ChenYCL** [comment]
亚马逊的要邮箱验证码
| |
陈宇轩
|
|
aa34913@126.com
|
签名由网易邮箱大师定制
在2019年2月17日 00:42，brokenman1<notifications@github.com> 写道：
https://www.hulu.com <https://www.hulu.com/>

dingqing6052732@163.com
gG123666

Amazon video

账号密码：dangua818@163.com----f78783368

HBO now:
账号 Buy1HBONOW@TBSS.CHWYYSJ <mailto:Buy1HBONOW@TBSS.CHWYYSJ> 密码chwyysj12

**Comment by ChenYCL** [comment]
@brokenman1  hulu和hbo可以了 亚马逊要你邮箱验证目前没弄

**Comment by brokenman1** [comment]
> @ brokenman1 hulu和hbo可以了亚马逊要你邮箱验证目前没弄

太历害了。。邮箱密码已私发到你的邮箱

**Comment by gykai** [comment]
您好，非常感谢您开发了这么优秀的程序。
有个问题想请教一下，目前测试Netflix和hulu正常，但是不知道为什么hbo now有问题，只能翻译出第一句话，后续的就不再显示了，而且第一句翻译出来的内容会一直显示在屏幕上，后面的原文字幕会继续显示，但不再翻译了。系统是win10 64位企业版，翻译的程序选过谷歌和百度，但都不能正常使用。再次感谢！
