### ISSUE TITLE
[翻译api] 费用问题

### ISSUE THREAD

**Issue by Ahao096** [ChenYCL/chrome-extension-udemy-translate#71]
作者考虑过直接抓网页翻译器的地址进行翻译吗,毕竟翻译字幕还要用接口服务,预赠的用完了就等于这个插件没用了

**Comment by ChenYCL** [comment]
暂时不考虑吧,第三方的服务会稳点,直接抓,浏览器层面很难跑,恐怕得假设node或者python服务了,如果可以欢迎提供 部署层面的脚本,那样可以解决这种情况了
