### ISSUE TITLE
hulu 不能翻译 版本百度网盘下的udemy-translate-v2.1.0

### ISSUE THREAD

**Issue by happy-lele** [ChenYCL/chrome-extension-udemy-translate#72]
<img width="1577" alt="截屏2021-01-19 02 58 11" src="https://user-images.githubusercontent.com/40606609/104954111-a1727780-5a02-11eb-928f-93ae0a1f288a.png">

**Comment by modernbaby** [comment]
我这里hulu也还是不能翻译，同样问题
![屏幕截图 2021-02-12 134249](https://user-images.githubusercontent.com/37820734/107734516-91fff900-6d38-11eb-8c98-8a19a1b85fbe.png)

**Comment by nccuiki** [comment]
加1

**Comment by lov3r** [comment]
+1

**Comment by ChenYCL** [comment]
修复 微信群测试
