### ISSUE TITLE
你好,我在使用HBO Max时发现会存在像素点.如图 

### ISSUE THREAD

**Issue by ShadowsSide** [ChenYCL/chrome-extension-udemy-translate#74]
![image](https://user-images.githubusercontent.com/61958350/109426584-6adc4380-7a29-11eb-9948-0c8aab46355d.png)

**Comment by ShadowsSide** [comment]
在其他流媒体网页使用时没有发现该情况.

**Comment by ChenYCL** [comment]
猜测是空字符串翻译了下 下次字幕出现会恢复正常么

**Comment by ShadowsSide** [comment]
只要原始字幕消失了,马赛克就消失了. 是原始字幕未能完全隐藏?? 我把背景透明调到了最大,原始字幕拉到了最小

**Comment by ChenYCL** [comment]
字体大小为0 那就是还有 只是看不到,背景色相当于容器 包裹字体的,效果就是一个没有文字的小格子了

**Comment by ShadowsSide** [comment]
> 字体大小为0 那就是还有 只是看不到,背景色相当于容器 包裹字体的,效果就是一个没有文字的小格子了

![image](https://user-images.githubusercontent.com/61958350/109635741-adb32e00-7b85-11eb-98e3-4cf9b8f4ff4c.png)
配置如上

**Comment by Dukewill** [comment]
在 hbo max 本身的字幕设置中把背景透明度设为 0%。

目前遇到的问题是，在下一句话出现前，目前的字幕不会消失。

**Comment by Chenjintao1997** [comment]
我在看HBO时候也有这个问题，楼主解决了吗

**Comment by Chenjintao1997** [comment]
我解决了 在字幕设置里面将透明度设为0就可以了
![image](https://user-images.githubusercontent.com/37171474/140104507-80fb1c42-5789-40db-a348-af41bc9681b4.png)
![image](https://user-images.githubusercontent.com/37171474/140104576-00b0fce4-17b8-45dc-9f7c-b120c8524dde.png)
