### ISSUE TITLE
HBO Max not be supported now?

### ISSUE THREAD

**Issue by ZyaireChu** [ChenYCL/chrome-extension-udemy-translate#77]
**Describe the "bug"**
It doesn't work on HBO Max, can not replace subtitle. I can only see the original subtitltes.

**Desktop**
 - OS: [Windows 10 20H2]
 - Browser: Chrome / Edge
 - Version: 88.0.4324.190 / Chromium 89.0.774.45

**Additional context**
Works fine on Netflix, I don't have other subscribe to test.

**Comment by ChenYCL** [comment]
fix now
