### ISSUE TITLE
麻烦支持下Skillshare这个网站,感激不尽

### ISSUE THREAD

**Issue by pxz666** [ChenYCL/chrome-extension-udemy-translate#78]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChenYCL** [comment]
近期弄

**Comment by pxz666** [comment]
谢谢

**Comment by ChenYCL** [comment]
有账号么 看了下要付费
