### ISSUE TITLE
能否自定义修改字幕样式，

### ISSUE THREAD

**Issue by brokenman1** [ChenYCL/chrome-extension-udemy-translate#8]
能否自定义修改字幕样式
包括字体颜色 大小，位置等。
那个hbo now不知道为什么字体是黑色的，有些看不清楚。
其它的网站都是白色的

**Comment by ChenYCL** [comment]
已经添加 @brokenman1

**Comment by brokenman1** [comment]
好的，感谢

ChenYCL <notifications@github.com> 于2019年2月23日周六 上午7:30写道：

**Comment by brokenman1** [comment]
当背景透明度设置为1以下时。把文字也透明掉了。如果设成0.1 几乎文字就看不到了，。这应该是个bug  希望修复
[](url)
