### ISSUE TITLE
Udemy视频字幕一行变双行，并且只翻译了第一行

### ISSUE THREAD

**Issue by huangyisan** [ChenYCL/chrome-extension-udemy-translate#93]
首先感谢作者！
目前在udemy使用的时候，发现存在一个问题。

插件版本：
2.1.4
使用api：
百度

原文为一行，使用插件之后，原文的一行变成两行，然后翻译的时候只翻译了第一行，第二行未翻译。
例如：
原文只有一行：the container in this part here. So we're going to make a network

开启插件后原文如下显示，变成两行:
the container in this part here.
So we're going to make a network.
这部分的容器。

第二行So we're going to make a network.没有进行翻译。

调整背景，原文译文大小，粗细钧无法解决。

再次感谢！

**Comment by huangyisan** [comment]
我尝试使用css样式插件添加white-space:nowrap属性，虽然两行变成一行，但翻译还是只翻译了第一行，可能在原始字幕读取的时候就是只获取到了第一行。
我所观看的视频为：https://www.udemy.com/course/istio-hands-on-for-kubernetes/  试看章节"what is istio?"

**Comment by ChenYCL** [comment]
好的
